let {
  viewExam,getExam,updateExamById,fetchExamById,viewExamById,examWiseQuestion,updateExam,deleteExam,deleteMultipleExam,createExam
 ,getQuestion,updateQuestionById,fetchQuestionById,viewQuestionById,updateQuestion,deleteQuestion,deleteMultipleQuestion,createQuestion,subjectMarks,getSubjectMarks,updateSubjectMarksById,fetchSubjectMarksById,viewSubjectMarksById,updateSubjectMarks,deleteSubjectMarks,deleteMultipleSubjectMarks,createSubjectMarks,fetchStudentAndSubjectByClass,assignExam
} = require("./exam");

module.exports = {
 viewExam,getExam,updateExamById,fetchExamById,viewExamById,examWiseQuestion,updateExam,deleteExam,deleteMultipleExam,createExam,getQuestion,updateQuestionById,fetchQuestionById,viewQuestionById,updateQuestion,deleteQuestion,deleteMultipleQuestion,createQuestion,subjectMarks,getSubjectMarks,updateSubjectMarksById,fetchSubjectMarksById,viewSubjectMarksById,updateSubjectMarks,deleteSubjectMarks,deleteMultipleSubjectMarks,createSubjectMarks,fetchStudentAndSubjectByClass,assignExam
};
