let {
   onlineTest,FullLengthTest,QuizTest,PracticeTest,getNewFulllengthTest,getCompletedFulllengthTest,getCompletedPracticeTest,getNewPracticeTest,getNewQuizTest,getCompletedQuizTest,viewExplaination,getQuestionExamWise,getFullLengthQuestion,getQuestionByIndex,getPracticeQuestion,getQuizQuestion,submitExam,saveNextQuestion,getAnsweredNotAnswered
 
} = require("./test-series");

module.exports = {
  onlineTest,FullLengthTest,QuizTest,PracticeTest,getNewFulllengthTest,getCompletedFulllengthTest,getCompletedPracticeTest,getNewPracticeTest,getNewQuizTest,getCompletedQuizTest,viewExplaination,getQuestionExamWise,getFullLengthQuestion,getPracticeQuestion,getQuestionByIndex,getQuizQuestion,submitExam,saveNextQuestion,getAnsweredNotAnswered
 
};
